
package com.wzc.RankDataService.GetRankService;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RankServiceImpl", targetNamespace = "http://com.wzc.RankDataService.RankServiceImpl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RankServiceImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRank")
    @WebResult(name = "GetRankReturn", targetNamespace = "http://com.wzc.RankDataService.RankServiceImpl", partName = "GetRankReturn")
    public String getRank();

}
