
package com.wzc.RankDataService.GetRankService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RankServiceImplService", targetNamespace = "http://com.wzc.RankDataService.RankServiceImpl", wsdlLocation = "http://localhost:8080/TestTerisWebGame_war_exploded/services/RankServiceImpl?wsdl")
public class RankServiceImplService
    extends Service
{

    private final static URL RANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RANKSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RANKSERVICEIMPLSERVICE_QNAME = new QName("http://com.wzc.RankDataService.RankServiceImpl", "RankServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TestTerisWebGame_war_exploded/services/RankServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RANKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RANKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RankServiceImplService() {
        super(__getWsdlLocation(), RANKSERVICEIMPLSERVICE_QNAME);
    }

    public RankServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RANKSERVICEIMPLSERVICE_QNAME, features);
    }

    public RankServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RANKSERVICEIMPLSERVICE_QNAME);
    }

    public RankServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RANKSERVICEIMPLSERVICE_QNAME, features);
    }

    public RankServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RankServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RankServiceImpl
     */
    @WebEndpoint(name = "RankServiceImpl")
    public RankServiceImpl getRankServiceImpl() {
        return super.getPort(new QName("http://com.wzc.RankDataService.RankServiceImpl", "RankServiceImpl"), RankServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RankServiceImpl
     */
    @WebEndpoint(name = "RankServiceImpl")
    public RankServiceImpl getRankServiceImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.wzc.RankDataService.RankServiceImpl", "RankServiceImpl"), RankServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RANKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RANKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
